#!/usr/bin/env Rscript

# Create the compact Phase 3.2 test layer:
# - CLI validation tests
# - one local R01 integration-smoke runner
# - GitHub Actions workflow for automated unit and CLI tests
#
# Run from the repository root:
#   Rscript scripts/setup_phase3_ci_smoke.R

project_root <- normalizePath(
  ".",
  winslash = "/",
  mustWork = TRUE
)

required_files <- c(
  "cancerppir.R",
  "R/load_all.R",
  "R/07_pipeline.R",
  "scripts/run_unit_tests.R",
  "scripts/compare_architecture_checkpoint_case.R",
  "renv.lock"
)

missing_files <- required_files[
  !file.exists(file.path(project_root, required_files))
]

if (length(missing_files) > 0L) {
  stop(
    paste0(
      "Run this script from the CancerPPIr repository root.\n",
      "Missing files:\n",
      paste0("- ", missing_files, collapse = "\n")
    ),
    call. = FALSE
  )
}

output_files <- c(
  "tests/testthat/test-cli.R",
  "scripts/run_r01_smoke_test.R",
  ".github/workflows/r-tests.yml"
)

existing_outputs <- output_files[
  file.exists(file.path(project_root, output_files))
]

if (length(existing_outputs) > 0L) {
  stop(
    paste0(
      "Phase 3.2 files already exist. Inspect them before rerunning setup:\n",
      paste0("- ", existing_outputs, collapse = "\n")
    ),
    call. = FALSE
  )
}

write_utf8 <- function(path, text) {
  dir.create(
    dirname(path),
    recursive = TRUE,
    showWarnings = FALSE
  )

  writeLines(
    enc2utf8(text),
    con = path,
    useBytes = TRUE
  )
}

test_cli <- c(
  "project_root <- Sys.getenv(",
  '  "CANCERPPIR_PROJECT_ROOT",',
  "  unset = normalizePath(",
  '    file.path("..", ".."),',
  '    winslash = "/",',
  "    mustWork = TRUE",
  "  )",
  ")",
  "",
  "cli_script <- file.path(",
  "  project_root,",
  '  "cancerppir.R"',
  ")",
  "",
  "rscript <- Sys.which(",
  '  "Rscript"',
  ")",
  "",
  "run_cli <- function(arguments = character()) {",
  "  output <- suppressWarnings(",
  "    system2(",
  "      command = rscript,",
  "      args = c(",
  "        shQuote(cli_script),",
  "        vapply(",
  "          arguments,",
  "          shQuote,",
  "          FUN.VALUE = character(1)",
  "        )",
  "      ),",
  "      stdout = TRUE,",
  "      stderr = TRUE",
  "    )",
  "  )",
  "",
  "  status <- attr(",
  "    output,",
  '    "status"',
  "  )",
  "",
  "  if (is.null(status)) {",
  "    status <- 0L",
  "  }",
  "",
  "  list(",
  "    status = as.integer(status),",
  "    output = output",
  "  )",
  "}",
  "",
  'testthat::test_that("CLI prints usage and fails when required arguments are absent", {',
  "  result <- run_cli()",
  "",
  "  testthat::expect_false(",
  "    identical(result$status, 0L)",
  "  )",
  "",
  "  testthat::expect_true(",
  "    any(grepl(",
  '      "Usage:",',
  "      result$output,",
  "      fixed = TRUE",
  "    ))",
  "  )",
  "})",
  "",
  'testthat::test_that("CLI rejects a missing input file before analysis", {',
  "  missing_input <- file.path(",
  "    tempdir(),",
  '    "cancerppir_missing_input.csv"',
  "  )",
  "",
  "  result <- run_cli(",
  "    c(",
  "      missing_input,",
  "      tempdir(),",
  "      tempdir(),",
  '      "400",',
  '      "30",',
  '      "TRUE"',
  "    )",
  "  )",
  "",
  "  testthat::expect_false(",
  "    identical(result$status, 0L)",
  "  )",
  "",
  "  testthat::expect_true(",
  "    any(grepl(",
  '      "Input file not found:",',
  "      result$output,",
  "      fixed = TRUE",
  "    ))",
  "  )",
  "})",
  "",
  'testthat::test_that("CLI rejects a non-positive score threshold", {',
  "  input_file <- tempfile(",
  '    fileext = ".csv"',
  "  )",
  "",
  "  writeLines(",
  "    c(",
  '      "gene,logFC,pvalue",',
  '      "TP53,1.5,0.01"',
  "    ),",
  "    input_file",
  "  )",
  "",
  "  result <- run_cli(",
  "    c(",
  "      input_file,",
  "      tempdir(),",
  "      tempdir(),",
  '      "0",',
  '      "30",',
  '      "TRUE"',
  "    )",
  "  )",
  "",
  "  testthat::expect_false(",
  "    identical(result$status, 0L)",
  "  )",
  "",
  "  testthat::expect_true(",
  "    any(grepl(",
  '      "score_threshold must be a positive integer.",',
  "      result$output,",
  "      fixed = TRUE",
  "    ))",
  "  )",
  "",
  "  unlink(input_file)",
  "})"
)

smoke_runner <- c(
  "#!/usr/bin/env Rscript",
  "",
  "# Run one local end-to-end R01 smoke test and compare it with the",
  "# frozen Phase 1 baseline.",
  "#",
  "# Optional positional arguments:",
  "#   1 baseline_root",
  "#   2 input_file",
  "#   3 cache_dir",
  "#   4 results_root",
  "#",
  "# Default invocation from the repository root:",
  "#   Rscript scripts/run_r01_smoke_test.R",
  "",
  "project_root <- normalizePath(",
  '  ".",',
  '  winslash = "/",',
  "  mustWork = TRUE",
  ")",
  "",
  "arguments <- commandArgs(",
  "  trailingOnly = TRUE",
  ")",
  "",
  "baseline_root <- if (length(arguments) >= 1L) {",
  "  arguments[[1L]]",
  "} else {",
  '  file.path("..", "results", "renv_phase1_full")',
  "}",
  "",
  "input_file <- if (length(arguments) >= 2L) {",
  "  arguments[[2L]]",
  "} else {",
  '  file.path("..", "input", "Genes_R.csv")',
  "}",
  "",
  "cache_dir <- if (length(arguments) >= 3L) {",
  "  arguments[[3L]]",
  "} else {",
  '  file.path("..", "string_cache")',
  "}",
  "",
  "results_root <- if (length(arguments) >= 4L) {",
  "  arguments[[4L]]",
  "} else {",
  '  file.path("..", "results", "phase3_r01_smoke")',
  "}",
  "",
  "required_paths <- c(",
  "  baseline_root,",
  "  input_file,",
  "  cache_dir",
  ")",
  "",
  "missing_paths <- required_paths[",
  "  !file.exists(required_paths)",
  "]",
  "",
  "if (length(missing_paths) > 0L) {",
  "  stop(",
  "    paste0(",
  '      "Required smoke-test paths are missing:\\n",',
  '      paste0("- ", missing_paths, collapse = "\\n")',
  "    ),",
  "    call. = FALSE",
  "  )",
  "}",
  "",
  "if (dir.exists(results_root)) {",
  "  stop(",
  "    paste0(",
  '      "Smoke-test output folder already exists: ",',
  "      results_root,",
  '      "\\nRemove it or provide a different fourth argument."',
  "    ),",
  "    call. = FALSE",
  "  )",
  "}",
  "",
  "dir.create(",
  "  file.path(results_root, \"logs\"),",
  "  recursive = TRUE,",
  "  showWarnings = FALSE",
  ")",
  "",
  "log_file <- file.path(",
  "  results_root,",
  '  "logs",',
  '  "R01.log"',
  ")",
  "",
  "rscript <- Sys.which(",
  '  "Rscript"',
  ")",
  "",
  "pipeline_status <- system2(",
  "  command = rscript,",
  "  args = c(",
  "    shQuote(",
  "      file.path(project_root, \"cancerppir.R\")",
  "    ),",
  "    shQuote(input_file),",
  "    shQuote(results_root),",
  "    shQuote(cache_dir),",
  '    "400",',
  '    "30",',
  '    "TRUE"',
  "  ),",
  "  stdout = log_file,",
  "  stderr = log_file",
  ")",
  "",
  "if (!identical(as.integer(pipeline_status), 0L)) {",
  "  stop(",
  "    paste0(",
  '      "R01 smoke pipeline failed with exit code ",',
  "      pipeline_status,",
  '      ". See: ",',
  "      log_file",
  "    ),",
  "    call. = FALSE",
  "  )",
  "}",
  "",
  "log_lines <- readLines(",
  "  log_file,",
  "  warn = FALSE,",
  '  encoding = "UTF-8"',
  ")",
  "",
  "required_log_fragments <- c(",
  '  "[CancerPPIr] Done.",',
  '  "[CancerPPIr] Mapped genes: 359/399 (90%)",',
  '  "[CancerPPIr] Network: 358 nodes, 4507 edges, 42 components"',
  ")",
  "",
  "missing_log_fragments <- required_log_fragments[",
  "  !vapply(",
  "    required_log_fragments,",
  "    function(fragment) {",
  "      any(grepl(",
  "        fragment,",
  "        log_lines,",
  "        fixed = TRUE",
  "      ))",
  "    },",
  "    FUN.VALUE = logical(1)",
  "  )",
  "]",
  "",
  "if (length(missing_log_fragments) > 0L) {",
  "  stop(",
  "    paste0(",
  '      "Smoke log is missing required completion evidence:\\n",',
  '      paste0("- ", missing_log_fragments, collapse = "\\n")',
  "    ),",
  "    call. = FALSE",
  "  )",
  "}",
  "",
  "error_patterns <- c(",
  '  "Error",',
  '  "failed",',
  '  "Execution halted",',
  '  "Выполнение остановлено"',
  ")",
  "",
  "if (any(vapply(",
  "  error_patterns,",
  "  function(pattern) {",
  "    any(grepl(",
  "      pattern,",
  "      log_lines,",
  "      ignore.case = TRUE",
  "    ))",
  "  },",
  "  FUN.VALUE = logical(1)",
  "))) {",
  "  stop(",
  "    paste0(",
  '      "Smoke log contains an error marker. See: ",',
  "      log_file",
  "    ),",
  "    call. = FALSE",
  "  )",
  "}",
  "",
  "expected_files <- file.path(",
  "  results_root,",
  '  "Genes_R",',
  "  c(",
  '    "CancerPPIr_Analytical_Report.xlsx",',
  '    "CancerPPIr_Technical_Report.xlsx",',
  '    "Network_for_Cytoscape.graphml",',
  '    "STRING_links.txt"',
  "  )",
  ")",
  "",
  "if (!all(file.exists(expected_files))) {",
  "  stop(",
  "    paste0(",
  '      "Smoke test did not produce all expected files:\\n",',
  "      paste0(",
  '        "- ",',
  "        expected_files[!file.exists(expected_files)],",
  '        collapse = "\\n"',
  "      )",
  "    ),",
  "    call. = FALSE",
  "  )",
  "}",
  "",
  "comparison_status <- system2(",
  "  command = rscript,",
  "  args = c(",
  "    shQuote(",
  "      file.path(",
  "        project_root,",
  '        "scripts",',
  '        "compare_architecture_checkpoint_case.R"',
  "      )",
  "    ),",
  "    shQuote(baseline_root),",
  "    shQuote(results_root),",
  '    "R01",',
  '    "Genes_R",',
  '    "phase_3_r01_smoke"',
  "  )",
  ")",
  "",
  "if (!identical(as.integer(comparison_status), 0L)) {",
  "  stop(",
  "    paste0(",
  '      "R01 baseline comparison failed with exit code ",',
  "      comparison_status,",
  '      "."',
  "    ),",
  "    call. = FALSE",
  "  )",
  "}",
  "",
  "summary_file <- file.path(",
  "  project_root,",
  '  "docs",',
  '  "architecture",',
  '  "phase_3_r01_smoke_summary.csv"',
  ")",
  "",
  "summary_table <- utils::read.csv(",
  "  summary_file,",
  "  stringsAsFactors = FALSE",
  ")",
  "",
  "stopifnot(",
  "  nrow(summary_table) == 1L,",
  "  isTRUE(summary_table$strict_regression_core_match[[1L]]),",
  "  summary_table$strict_sheets_compared[[1L]] == 12L,",
  "  summary_table$strict_sheets_identical[[1L]] == 12L",
  ")",
  "",
  'cat("PHASE 3.2 R01 SMOKE TEST PASSED: 12/12 STRICT SHEETS\\n")'
)

workflow <- c(
  "name: R tests",
  "",
  "on:",
  "  push:",
  "  pull_request:",
  "",
  "permissions:",
  "  contents: read",
  "",
  "jobs:",
  "  unit-and-cli-tests:",
  "    runs-on: ubuntu-24.04",
  "    timeout-minutes: 45",
  "",
  "    env:",
  "      RENV_CONFIG_REPOS_OVERRIDE: https://cloud.r-project.org",
  "",
  "    steps:",
  "      - name: Check out repository",
  "        uses: actions/checkout@v6",
  "",
  "      - name: Set up R",
  "        uses: r-lib/actions/setup-r@v2",
  "        with:",
  "          r-version: '4.5.0'",
  "          use-public-rspm: true",
  "",
  "      - name: Install Linux runtime libraries",
  "        run: |",
  "          sudo apt-get update",
  "          sudo apt-get install -y --no-install-recommends libglpk40",
  "",
  "      - name: Restore renv environment",
  "        uses: r-lib/actions/setup-renv@v2",
  "",
  "      - name: Verify renv status",
  "        run: Rscript -e \"renv::status()\"",
  "",
  "      - name: Run unit and CLI tests",
  "        run: Rscript scripts/run_unit_tests.R"
)

files <- list(
  "tests/testthat/test-cli.R" = test_cli,
  "scripts/run_r01_smoke_test.R" = smoke_runner,
  ".github/workflows/r-tests.yml" = workflow
)

for (r_file in c(
  "tests/testthat/test-cli.R",
  "scripts/run_r01_smoke_test.R"
)) {
  temporary_r_file <- tempfile(fileext = ".R")
  writeLines(
    files[[r_file]],
    con = temporary_r_file,
    useBytes = TRUE
  )
  invisible(parse(file = temporary_r_file))
  unlink(temporary_r_file, force = TRUE)
}

for (relative_path in names(files)) {
  write_utf8(
    file.path(project_root, relative_path),
    files[[relative_path]]
  )
}

message("[phase 3.2 setup] CLI tests created.")
message("[phase 3.2 setup] Local R01 smoke runner created.")
message("[phase 3.2 setup] GitHub Actions workflow created.")
message("[phase 3.2 setup] No analytical source files were modified.")