# CancerPPIr public schema registry
#
# Single runtime source of public output-schema versions.
# Release validators retain independent pinned expectations.

CANCERPPIR_PIPELINE_RESULT_SCHEMA_VERSION <- "1.0.0"
CANCERPPIR_BIOLOGICAL_EVIDENCE_SCHEMA_VERSION <- "1.0.0"
CANCERPPIR_ANALYTICAL_SCHEMA_VERSION <- "2.0.0"
CANCERPPIR_TECHNICAL_WORKBOOK_SCHEMA_VERSION <- "1.0.0"
CANCERPPIR_GRAPHML_SCHEMA_VERSION <- "1.0.0"
CANCERPPIR_OUTPUT_MANIFEST_SCHEMA_VERSION <- "2.1.0"
CANCERPPIR_OUTPUT_CHECKSUMS_SCHEMA_VERSION <- "1.0.0"

CANCERPPIR_SUPPORTED_OUTPUT_MANIFEST_SCHEMA_VERSIONS <- c(
  "1.0.0",
  "2.0.0",
  CANCERPPIR_OUTPUT_MANIFEST_SCHEMA_VERSION
)

CANCERPPIR_PUBLIC_SCHEMA_VERSIONS <- list(
  pipeline_result = CANCERPPIR_PIPELINE_RESULT_SCHEMA_VERSION,
  biological_evidence = CANCERPPIR_BIOLOGICAL_EVIDENCE_SCHEMA_VERSION,
  analytical_workbook = CANCERPPIR_ANALYTICAL_SCHEMA_VERSION,
  technical_workbook = CANCERPPIR_TECHNICAL_WORKBOOK_SCHEMA_VERSION,
  graphml = CANCERPPIR_GRAPHML_SCHEMA_VERSION,
  output_manifest = CANCERPPIR_OUTPUT_MANIFEST_SCHEMA_VERSION,
  output_checksums = CANCERPPIR_OUTPUT_CHECKSUMS_SCHEMA_VERSION
)

cancerppir_schema_versions <- function() {
  CANCERPPIR_PUBLIC_SCHEMA_VERSIONS
}
